---
geometry: margin=0.75cm
output: pdf_document
---


```{r setup, include=FALSE, results='asis'}
library(kableExtra)
library(formattable)
library(here)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
options(knitr.kableExtra.NA = '')
```


```{r}
#Read in counts and cvr data
counts <- read.csv(here("results/counts.csv"), row.names=1, stringsAsFactors = FALSE)
cvr <- read.csv(here("results/cvr.csv"), row.names=1, stringsAsFactors = FALSE)



#Grab data from counts
col_nams <- colnames(cvr)
row_nams <- rownames(cvr)
labs = counts$lab

#Remove other metadeta from counts data
counts <- data.frame(matrix(as.numeric(unlist(counts)), nrow = nrow(counts)))
colnames(counts) <- col_nams
counts <- counts[,-c(20,19,18, 17)]
rownames(counts) <- row_nams


#Separate datasets by lab
lab_specific_cvr = list()
lab_specific_counts = list()

for(lab_name in unique(labs)){
  lab_counts = counts[labs == lab_name,]
  lab_cvr = cvr[labs == lab_name,]
  
  rownames(lab_counts) = rownames(counts)[labs == lab_name]
  rownames(lab_cvr) = rownames(cvr)[labs == lab_name]
  
  lab_specific_cvr[[lab_name]] = lab_cvr
  lab_specific_counts[[lab_name]] = lab_counts
}


```


<!-- Process Coverage Data -->


```{r, echo=FALSE}
#Set up colors palette for coverage data
max.val = log(400001)
pal.fnc = colorRamp(c("red","lemonchiffon", "green"))

for(lab_cvr_num in 1:3){
  lab_cvr = lab_specific_cvr[[lab_cvr_num]]
  
  lab_cvr[1:ncol(lab_cvr)] <- lapply (lab_cvr[1:ncol(lab_cvr)], function(x){
    cell_spec(x, color = "black", background = rgb(pal.fnc(log(x+1)/max.val) %>% replace(., is.na(.), 200), maxColorValue=255))
  })
  
  lab_specific_cvr[[lab_cvr_num]] = lab_cvr
}
```


<!-- Plot each lab's coverage data -->

```{r}
 kbl(lab_specific_cvr[["guelph"]], escape = F, align = "c", longtable = TRUE, caption = "Coverage from Guelph Laboratory") %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(cvr)+1), width = "0.62cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```


\pagebreak


```{r}
 kbl(lab_specific_cvr[["waterloo"]], escape = F, align = "c", longtable = TRUE, caption = "Coverage from Waterloo Laboratory") %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(cvr)+1), width = "0.62cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```


\pagebreak


```{r}
 kbl(lab_specific_cvr[["western"]], escape = F, align = "c", longtable = TRUE, caption = "Coverage from Western Laboratory") %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(cvr)+1), width = "0.62cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```

\pagebreak





<!-- Process Mutation Data -->
```{r, echo=FALSE}
#Set up colors palette for counts data
max.val = log(800)
pal.fnc = colorRamp(c("green","lemonchiffon", "red"))

for(lab_count_num in 1:3){
  lab_counts = lab_specific_counts[[lab_count_num]]
  View(lab_counts)
  
  cells = data.frame(matrix(nrow = nrow(lab_counts), ncol = ncol(lab_counts)))
  rownames(cells) = rownames(lab_counts)
  colnames(cells) = colnames(lab_counts)
  for (i in (1:nrow(lab_counts))){
    for(j in (1:ncol(lab_counts))){
      cell = lab_counts[i,j]
      if (is.na(cell)){
          new_cell = cell_spec(" ", color = "black", background = "white")
      }
      else{
          new_cell = cell_spec(cell, color = "black", background = rgb(pal.fnc(log(cell+1)/max.val) %>% replace(., is.na(.), 255), maxColorValue=255))
      }
      cells[i,j] = new_cell
    }
  }
  lab_specific_counts[[lab_count_num]] = cells
}
```


<!-- Plot each lab's coverage data -->

```{r}


 kbl(lab_specific_counts[["guelph"]], escape = F, align = "c", longtable = TRUE, caption = "Omicron Counts from Guelph Laboratory" ) %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(cvr)+1), width = "0.62cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```


\pagebreak


```{r}
 kbl(lab_specific_counts[["waterloo"]], escape = F, align = "c", longtable = TRUE, caption = "Omicron Mutation Counts from Waterloo Laboratory") %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(cvr)+1), width = "0.62cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```


\pagebreak


```{r}
 kbl(lab_specific_counts[["western"]], escape = F, align = "c", longtable = TRUE, caption = "Omicron Mutation Counts from Western Laboratory") %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(cvr)+1), width = "0.62cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```



