---
geometry: margin=0.75cm
output:
  pdf_document: default
  html_document:
    df_print: paged
params:
  input: None
---


```{r setup, include=FALSE, results='asis'}
if (params$input == "None") {
  stop("\n\nUsage: Rscript -e \"rmarkdown::render('scripts/summarize-data.Rmd', params = list(input = [input JSON]), output_file = [output PDF])\" \n",
       "    input JSON:  JSON generated by estimate-freqs.R\n") 
}

library(jsonlite)
library(kableExtra)
library(formattable)
library(here)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
options(knitr.kableExtra.NA = '')
```


```{r}
json <- jsonlite::fromJSON(here(params$input))
filename <- basename(params$input)
coverage <- json$coverage

#Set up colors palette for coverage data
max.val = log(max(coverage, na.rm = TRUE) + 10000)
pal.fnc = colorRamp(c("red","lemonchiffon", "green"))

coverage[1:ncol(coverage)] <- lapply (coverage[1:ncol(coverage)], function(x){
  cell_spec(x, color = "black", background = rgb(pal.fnc(log(x+1)/max.val) %>% replace(., is.na(.), 200), maxColorValue=255))
})

kbl(coverage, escape = F, align = "c", longtable = TRUE, caption = paste("Coverage from ", filename)) %>%
  kable_paper("basic", full_width = F) %>%
    kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(coverage)+1), width = "0.48cm") %>%
      column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)

```

\pagebreak

```{r}
counts <- json$counts

col_names <- colnames(counts)
row_names <- rownames(counts)

counts <- data.frame(matrix(as.numeric(unlist(counts)), nrow = nrow(counts)))
colnames(counts) <- col_names
rownames(counts) <- row_names

#Set up colors palette for counts data
max.val = log(max(counts, na.rm = TRUE) + 10000)
pal.fnc = colorRamp(c("green","lemonchiffon", "red"))

cells = data.frame(matrix(nrow = nrow(counts), ncol = ncol(counts)))
rownames(cells) = rownames(counts)
colnames(cells) = colnames(counts)
for (i in (1:nrow(counts))){
  for(j in (1:ncol(counts))){
    cell = counts[i,j]
    if (is.na(cell)){
        new_cell = cell_spec(" ", color = "black", background = "white")
    }
    else{
        new_cell = cell_spec(cell, color = "black", background = rgb(pal.fnc(log(cell+1)/max.val) %>% replace(., is.na(.), 255), maxColorValue=255))
    }
    cells[i,j] = new_cell
  }
}
counts = cells

kbl(counts, escape = F, align = "c", longtable = TRUE, caption = paste("Counts from ", filename)) %>%
kable_paper("basic", full_width = F) %>%
  kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% column_spec(2:(ncol(counts)+1), width = "0.48cm") %>%
    column_spec(1, width = "2cm") %>% row_spec(0,angle = 90)
```